tosca_definitions_version: cloudify_dsl_1_3

imports:
- http://www.getcloudify.org/spec/cloudify/3.4.2/types.yaml
- http://www.getcloudify.org/spec/aws-plugin/1.4.6/plugin.yaml
- plugin.yaml

inputs:

  aws_access_key_id:
    type: string

  aws_secret_access_key:
    type: string

  aws_region_name:
    type: string
    default: us-east-1

dsl_definitions:

  client_config: &client_config
    aws_access_key_id: { get_input: aws_access_key_id }
    aws_secret_access_key: { get_input: aws_secret_access_key }
    region_name: { get_input: aws_region_name }

  aws_config: &aws_config
    aws_access_key_id: { get_input: aws_access_key_id }
    aws_secret_access_key: { get_input: aws_secret_access_key }
    ec2_region_name: { get_input: aws_region_name }

node_templates:

  forward_rule:
    type: cloudify.nodes.aws.elb.Rule
    properties:
      resource_config:
        kwargs:
          Priority: 101
          Conditions:
            - Field: 'host-header'
              Values:
                - example.com
          Actions:
            - Type: forward
              TargetGroupArn: forward_target_group
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: vpc
    - type: cloudify.relationships.depends_on
      target: http_listener
    - type: cloudify.relationships.depends_on
      target: forward_target_group

  forward_target_group:
    type: cloudify.nodes.aws.elb.TargetGroup
    properties:
      resource_config:
        kwargs:
          Name: test-elb-target-group
          Protocol: HTTP
          Port: 8080
          HealthCheckProtocol: HTTP
          HealthCheckPort: '80'
          HealthCheckIntervalSeconds: 30
          HealthCheckTimeoutSeconds: 5
          UnhealthyThresholdCount: 3
          Matcher:
            HttpCode: '404'
          Attributes:
            - Key: stickiness.enabled
              Value: 'true'
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: vpc

  http_listener:
    type: cloudify.nodes.aws.elb.Listener
    properties:
      resource_config:
        kwargs:
          Protocol: HTTP
          Port: 8080
          # SslPolicy: SSLNegotiationPolicyType
          DefaultActions:
            - Type: forward
              TargetGroupArn: arn:aws:elasticloadbalancing:eu-west-1:535075449278:targetgroup/TEST/c46b448a282b8c9a
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: elb

  elb:
    type: cloudify.nodes.aws.elb.LoadBalancer
    properties:
      resource_config:
        kwargs:
          Name: test-elb
          Attributes:
            - Key: idle_timeout.timeout_seconds
              Value: '120'
            # Untested
            # - Key: access_logs.s3.enabled
            #   Value: true
            # - Key: access_logs.s3.bucket
            #   Value: bucket-name
      client_config: *client_config
    relationships:
    - type: cloudify.relationships.depends_on
      target: subnet1
    - type: cloudify.relationships.depends_on
      target: subnet2
    - type: cloudify.relationships.depends_on
      target: subnet3
    - type: cloudify.relationships.depends_on
      target: security_group

  security_group:
    type: cloudify.aws.nodes.SecurityGroup
    properties:
      aws_config: *aws_config
      use_external_resource: true
      resource_id: sg-8aaf7bef
      description: default security group
      rules: []
    relationships:
    - type: cloudify.aws.relationships.security_group_contained_in_vpc
      target: vpc

  subnet1:
    type: cloudify.aws.nodes.Subnet
    properties:
      aws_config: *aws_config
      use_external_resource: true
      resource_id: subnet-b545b1c2
      cidr_block:  172.30.0.0/24
      availability_zone: eu-west-1a
    relationships:
    - type: cloudify.aws.relationships.subnet_contained_in_vpc
      target: vpc

  subnet2:
    type: cloudify.aws.nodes.Subnet
    properties:
      aws_config: *aws_config
      use_external_resource: true
      resource_id: subnet-0c9b5369
      cidr_block:  172.30.1.0/24
      availability_zone: eu-west-1b
    relationships:
    - type: cloudify.aws.relationships.subnet_contained_in_vpc
      target: vpc

  subnet3:
    type: cloudify.aws.nodes.Subnet
    properties:
      aws_config: *aws_config
      use_external_resource: true
      resource_id: subnet-1f909a59
      cidr_block:  172.30.2.0/24
      availability_zone: eu-west-1c
    relationships:
    - type: cloudify.aws.relationships.subnet_contained_in_vpc
      target: vpc

  vpc:
    type: cloudify.aws.nodes.VPC
    properties:
      aws_config: *aws_config
      use_external_resource: true
      resource_id: vpc-ffec199a
      cidr_block:  172.30.0.0/16
